core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    # path("error", handler500, name="error")

]

if settings.DEBUG:
    #     urlpatterns += static(settings.STATIC_URL,
    #                           document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

icjcf/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import Register

urlpatterns = [
    path('adminicjcf/', admin.site.urls),
    path('accounts/register', Register.as_view(), name="register"),
    path('accounts/', include('allauth.urls')),
    path("resourcecenter/", include("resourcecenter.urls")),
    path("", include("core.urls")),
]

handler404 = "core.views.handler404"
handler500 = "core.views.handler500"
handler400 = "core.views.handler400"
handler403 = "core.views.handler403"

resourcecenter/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django_downloadview import ObjectDownloadView

from .views import TestView, Upload, Home, DownloadList, DownloadView, Upvote, Downvote, DeleteFile, MyAccount, Profile, ReportView, Terms, MessageView, StatisticsView, traffic_counter, traffic_counter_info
from .models import File
from .sitemaps import sitemaps

app_name = "resourcecenter"

download = ObjectDownloadView.as_view(model=File, file_field='file')

urlpatterns = [
    path("", Home.as_view(), name="home"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    #     path("test/", TestView.as_view(), name="test"),
    path("upload/", Upload.as_view(), name="upload"),
    path("terms/", Terms.as_view(), name="terms"),
    path("message/send/", MessageView.as_view(), name="message"),
    path("account/", MyAccount.as_view(), name="my_account"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path("traffic/counter", traffic_counter, name="traffic"),
    path("traffic/counter/info", traffic_counter_info, name="traffic_info"),
    path("profile/<str:username>/", Profile.as_view(), name="profile"),
    path("download/<str:department>/<str:level>/",
         DownloadList.as_view(), name="downloadlist"),
    path("download/<str:department>/<str:level>/<slug>/",
         DownloadView.as_view(), name="download"),
    path("report/<slug>/", ReportView.as_view(), name="report"),
    path("delete/<slug>/<int:delete_id>/",
         DeleteFile.as_view(), name="deletefile"),
    path("upvote/<str:department>/<str:level>/<slug>/",
         Upvote.as_view(), name="upvote"),
    path("downvote/<str:department>/<str:level>/<slug>/",
         Downvote.as_view(), name="downvote"),
    url('^download/(?P<slug>[A-Za-z0-9_-]+)/$',
        download, name='download_file'),

]

resourcecenter/forms.py
from django import forms


class UploadForm(forms.Form):
    department = forms.CharField(max_length=20)
    level = forms.CharField(max_length=30)
    courseCode = forms.CharField(max_length=8, required=False)
    description = forms.CharField(max_length=20, required=False)
    semester = forms.CharField(max_length=1, required=False)


class UpdateProfileForm(forms.Form):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    department = forms.CharField()
    level = forms.CharField()
    phone = forms.CharField(required=False)


class ReportFileForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    file_name = forms.CharField()
    reason = forms.CharField(required=False)


class MessageForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    message = forms.CharField()

resourcecenter/views.py
from django.http.response import Http404, HttpResponse
from django.shortcuts import render
from django.views.generic import View, ListView
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from django.utils import timezone
from django.db.models import Sum

from operator import methodcaller
import random
import botocore


from .forms import UploadForm, UpdateProfileForm, ReportFileForm, MessageForm
from .models import File, NonAcademicLevel, Report, Message, Traffic

from core.models import Department, Level, Student


class Home(View):
    def get(self, *args, **kwargs):
        context = {

        }
        return render(self.request, "rchome.html", context)


class Upload(View):
    def get(self, *args, **kwargs):
        context = {

        }
        return render(self.request, "uploadfile.html", context)

    def post(self, *args, **kwargs):
        form = UploadForm(self.request.POST or None)
        if form.is_valid():
            files = self.request.FILES.getlist("userUpload")

            department = form.cleaned_data.get("department")
            level = form.cleaned_data.get("level")
            courseCode = form.cleaned_data.get("courseCode").upper()
            description = form.cleaned_data.get("description")
            semester = form.cleaned_data.get("semester")

            count = 0
            uploads = []

            for file in files:
                if file.size <= 52428800:
                    if department != "nonAcademic" and department != "---SELECT DEPARTMENT---":
                        delete_id = random.randint(1000000, 99999999)
                        upload = File.objects.create(file=file, file_name=file.name, department=department.upper(
                        ), level=level, courseCode=courseCode, description=description, semester=semester, uploader=self.request.user.__str__(), delete_id=delete_id)
                    elif department == "nonAcademic":
                        delete_id = random.randint(1000000, 99999999)
                        upload = File.objects.create(
                            file=file, file_name=file.name, department=department, level=level, uploader=self.request.user.__str__(), delete_id=delete_id)

                    count += 1
                    uploads.append(upload)
                else:
                    messages.warning(
                        self.request, f"{file.name} exceeds the allowable file size")

            if self.request.user.is_authenticated:
                student = Student.objects.get(user=self.request.user)
                for upload in uploads:
                    student.files.add(upload)
                student.save()

            if count > 0:
                messages.success(
                    self.request, f"Successfully Uploaded {count} file(s)")

            context = {
                "uploads": uploads,
            }
            return render(self.request, "uploadsuccess.html", context)
        else:
            messages.warning(self.request, "Form is invalid")
            return redirect("resourcecenter:upload")


class DownloadList(ListView):
    template_name = "downloadlist.html"

    def get_queryset(self, **kwargs):
        if self.kwargs['department'].upper() == "NONACADEMIC":
            self.department = self.kwargs['department']
            self.level = get_object_or_404(
                NonAcademicLevel, id=self.kwargs['level'])
            return File.objects.filter(department=self.department, level=self.level.name).order_by("-id")
        else:
            self.department = get_object_or_404(
                Department, abbreviation=self.kwargs['department'].upper())
            self.level = get_object_or_404(
                Level, level_id=self.kwargs['level'])
            return File.objects.filter(department=self.department.abbreviation, level=self.level.__str__()).order_by("-id")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.kwargs['department'].upper() == "NONACADEMIC":
            context.update({
                "level": get_object_or_404(
                    NonAcademicLevel, id=self.kwargs['level']).name
            })
        else:
            context.update({
                "department": self.kwargs["department"].upper(),
                "level": f" {self.kwargs['level']} Level",
            })
        return context


class DownloadView(View):
    def get(self, *args, **kwargs):
        try:
            file_object = get_object_or_404(File, slug=kwargs["slug"])
        except File.MultipleObjectsReturned:
            files = File.objects.filter(slug=kwargs["slug"])
            for file in files:
                file.reslug()
            file_object = files[0]
        context = {
            "object": file_object,
        }
        try:
            return render(self.request, "download.html", context)
        except botocore.exceptions.ClientError as error:
            if error.response['Error']['Code'] == "404":
                file_object.delete()
            else:
                return render(self.request, "download.html", context)

    def post(self, *args, **kwargs):
        file_object = get_object_or_404(File, slug=kwargs["slug"])
        file_object.downloads += 1
        file_object.save()
        return redirect("resourcecenter:download_file", slug=file_object.slug)


class Upvote(View):
    def post(self, *args, **kwargs):
        file_object = get_object_or_404(File, slug=kwargs["slug"])
        if self.request.user.is_authenticated:
            file_object.upvotes += 1
            file_object.save()
            messages.success(self.request, "File Successfully upvoted")
        else:
            messages.warning(
                self.request, "You must be logged in to perform this action")
        return redirect("resourcecenter:download", department=kwargs["department"], level=kwargs["level"], slug=kwargs["slug"])


class Downvote(View):
    def post(self, *args, **kwargs):
        file_object = get_object_or_404(File, slug=kwargs["slug"])
        if self.request.user.is_authenticated:
            file_object.downvotes += 1
            file_object.save()
            messages.success(self.request, "File Successfully downvoted")
        else:
            messages.warning(
                self.request, "You must be logged in to perform this action")
        return redirect("resourcecenter:download", department=kwargs["department"], level=kwargs["level"], slug=kwargs["slug"])


class DeleteFile(View):
    def get(self, *args, **kwargs):
        file_object = get_object_or_404(
            File, slug=kwargs["slug"], delete_id=kwargs["delete_id"])
        context = {
            "object": file_object,
        }
        return render(self.request, "deletefile.html", context)

    def post(self, *args, **kwargs):
        file_object = get_object_or_404(
            File, slug=kwargs["slug"], delete_id=kwargs["delete_id"])
        department = file_object.department
        level = file_object.level
        file_object.delete()
        messages.success(self.request, "File Successfully Deleted")
        if department.upper() == "NONACADEMIC":
            n_a_l = NonAcademicLevel.objects.get(name=level)
            level = n_a_l.id
        return redirect("resourcecenter:downloadlist", department=department, level=level)


class MyAccount(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        student = Student.objects.get(user=self.request.user)
        context = {
            "student": student,
        }
        return render(self.request, "my_account.html", context)

    def post(self, *args, **kwargs):
        form = UpdateProfileForm(self.request.POST or None)
        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            department = form.cleaned_data.get("department").upper()
            level = form.cleaned_data.get("level")
            phone = form.cleaned_data.get("phone")

            try:
                dept = Department.objects.get(abbreviation=department)
                level = Level.objects.get(level_id=level)
                student = Student.objects.get(user=self.request.user)

                student.first_name = first_name
                student.last_name = last_name
                student.department = dept
                student.level = level
                student.phone = phone
                student.save()

                messages.success(self.request, "Profile Successfully updated")
            except:
                messages.error(self.request, "Something went wrong")
        return redirect("resourcecenter:my_account")


class Profile(View):
    def get(self, *args, **kwargs):
        user = get_object_or_404(User, username=kwargs["username"])
        student = get_object_or_404(Student, user=user)
        context = {
            "student": student,
        }
        return render(self.request, "profile.html", context)


class ReportView(View):
    def get(self, *args, **kwargs):
        file_object = get_object_or_404(File, slug=kwargs["slug"])
        context = {
            "file": file_object,
        }
        return render(self.request, "reportfile.html", context)

    def post(self, *args, **kwargs):
        form = ReportFileForm(self.request.POST or None)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            reason = form.cleaned_data.get("reason")

            file_object = get_object_or_404(File, slug=kwargs["slug"])
            Report.objects.create(name=name, email=email,
                                  reason=reason, file=file_object)

resourcecenter/templates/base.html
{% load static %}
{% load rc_template_tags %}
<!DOCTYPE HTML>
<html>

<head>
	<title>{% block title %}Resource Center{% endblock title %}</title>
	<meta charset="utf-8" />
	<meta name="description"
		content="{% block description %}Resource Center, a free open Courseware powered by ICJCF for every FUNAAB student.	Explore, Share and Store Academic Resources Easily.{% endblock description %}">

	<meta property="og:locale" content="en_US">
	<meta property="og:type" content="website">
	<meta property="og:url" content="https://resourcecenter.com.ng/">
	<meta property="og:site_name" content="ResourceCenter">

	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
	<noscript>
		<link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	<link rel="manifest" href="{% static 'icons/webicons/site.webmanifest' %}">
	<link rel="shortcut icon" href="{% static 'icons/webicons/favicon.ico' %}" type="image/x-icon">
	<link rel="apple-touch-icon" href="{% static 'icons/webicons/apple-touch-icon.png' %}">
	<style>
		@media screen and (max-width: 736px) {
			.is-preload .wrapper #intro {
				min-height: 50vh
			}
		}
	</style>
	{% block extra_head %}
	{% endblock extra_head %}

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-N0HKZMYBTL"></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}
		gtag('js', new Date());

		gtag('config', 'G-N0HKZMYBTL');
	</script>
	<script type='text/javascript'
		src='//pl17233998.safestgatetocontent.com/b5/06/5d/b5065d8f98c1fa789de0afd29004d7cb.js'>
	</script>
</head>

<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper" class="fade-in">
		<div class="col-sm-12">
			{% if messages %}
			{% for message in messages %}
			<div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}
                     alert-dismissible fade show" role="alert">
				<span
					class="badge badge-pill badge-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}">{{message.tags}}</span>{{message}}
			</div>
			{% endfor %}
			{% endif %}
		</div>
		{% block intro %}

		{% endblock intro %}
		<!-- Header -->
		<header id="header">
			<a href="{% url 'resourcecenter:home' %}" class="logo">Resource Center</a>
		</header>

		<!-- Nav -->
		<nav id="nav">
			<ul class="links">
				<li><a href="{% url 'resourcecenter:home' %}">Resource Center</a></li>
				{% if request.user.is_authenticated %}
				{{request.user|downloadlist_shortcut|safe}}
				{% endif %}
				<li id="upload-nav"><a href="{% url 'resourcecenter:upload' %}">Upload File(s)</a></li>
				{% if request.user.is_authenticated %}
				<li><a href="{% url 'resourcecenter:my_account' %}">My Account</a></li>
				{% else %}
				<li><a href="{% url 'account_login' %}">Sign in</a></li>
				<li><a href="{% url 'account_signup' %}">Sign up</a></li>
				{% endif %}
				<li><a href="{% url 'resourcecenter:statistics' %}">Statistics</a></li>

			</ul>
			<ul class="icons">
				<li><a href="https://twitter.com/icjcf_funaab" target="blank_" title="@icjcf_funaab"
						class="icon brands fa-twitter"><span class="label">Twitter</span></a>
				</li>
				<li><a href="https://fb.me/icjcffunaab" target="blank_" title="@icjcfFunaab"
						class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
				<li><a href="https://www.instagram.com/icjcf_funaab" target="blank_" title="@icjcf_funaab"
						class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
			</ul>
		</nav>

		<!-- Main -->
		<div id="main">
			{% block content %}
			{% endblock content %}
		</div>

		<!-- Footer -->
		<footer id="footer">
			<section>
				<form method="post" action="{% url 'resourcecenter:message' %}">
					{% csrf_token %}
					<div class="fields">
						<div class="field">
							<label for="name">Name</label>
							<input type="text" name="name" id="name" />
						</div>
						<div class="field">
							<label for="email">Email</label>
							<input type="text" name="email" id="email" />
						</div>
						<div class="field">
							<label for="message">Message</label>
							<textarea name="message" id="message" rows="3" required></textarea>
						</div>
					</div>
					<ul class="actions">
						<li><input class="button primary" type="submit" value="Send Message" /></li>
					</ul>
				</form>
			</section>
			<section class="split contact">
				<section class="alt">
					<h3>Address</h3>
					<p>Federal University of Agriculture,<br />
						Abeokuta.</p>
				</section>
				<section>
					<h3>Phone</h3>
					<p><a href="#">0817 910 8512</a></p>
				</section>
				<section>
					<h3>Email</h3>
					<p><a href="#">icjcf_unaab@yahoo.com</a></p>
				</section>
				<section>
					<h3>Social</h3>
					<ul class="icons alt">
						<li><a href="https://twitter.com/icjcf_funaab" target="blank_" title="@icjcf_funaab"
								class="icon brands alt fa-twitter"><span class="label">Twitter</span></a>
						</li>
						<li><a href="https://fb.me/icjcffunaab" target="blank_" title="@icjcfFunaab"
								class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
						<li><a href="https://www.instagram.com/icjcf_funaab" target="blank_" title="@icjcf_funaab"
								class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
					</ul>
				</section>
			</section>
		</footer>

		<!-- Copyright -->
		<div id="copyright">
			<ul>
				<li>&copy; Resource Center</li>
				<li>Powered by: <a href="#" class="scrolly">ICJCF</a></li>
			</ul>
		</div>

	</div>

	<script src="{% static 'assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
	<script src="{% static 'assets/js/browser.min.js' %}"></script>
	<script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
	<script src="{% static 'assets/js/util.js' %}"></script>
	<script src="{% static 'assets/js/main.js' %}"></script>

	<script>
		if (document.location.pathname == "/resourcecenter/upload") {
			document.getElementById("upload-nav").classList.add("active")
		}
	</script>
	<script>
		$("document").ready(function () {
			setTimeout(function () {
				$(".alert").fadeOut()
			}, 5000)

		})
	</script>
	<script>
		$(document).ready(function () {
			let url = "{% url 'resourcecenter:traffic' %}"
			let request = new XMLHttpRequest();
			request.open("GET", url);
			request.send()
		})
	</script>
	{% block extra_scripts %}
	{% endblock extra_scripts %}

</body>

</html>

resourcecenter/templates/deletefile.html
{% extends 'base.html' %}
{% load static %}
{% load rc_template_tags %}

{% block extra_head %}

{% endblock extra_head %}

{% block title %}Delete File{% endblock title %}


{% block content %}
<div>
    <h2>Are you sure you want to delete this File?</h2>
    <h4>{{object.file.name|clean_title}}</h4>
    <a href="{{object.get_download_url}}" class="button mr-3">No</a>
    <form style="display: inline;" action="" method="post"> {% csrf_token %} <button type="submit">Yes</button></form>

</div>
{% endblock content %}


{% block extra_scripts %}

{% endblock extra_scripts %}

resourcecenter/templates/my_account.html
{% extends 'base.html' %}
{% load static %}
{% load rc_template_tags %}
{% load i18n %}

{% block extra_head %}

{% endblock extra_head %}

{% block title %}My Account{% endblock title %}

{% block content %}
<section class="post pt-3">
    <header class="major mb-3">
        <span class="date mt-3 mb-0" style="font-weight: 600;">
            User Profile
        </span>
    </header>
    <div>
        <table id="user_profile">
            <tbody>
                <tr>
                    <td style="font-weight: 600">Name</td>
                    <td>{{student.name}}</td>
                </tr>
                <tr>
                    <td style="font-weight: 600">Department</td>
                    <td>{{student.department.name}}</td>
                </tr>
                <tr>
                    <td style="font-weight: 600">Knowledge Points</td>
                    <td>{{student.knowledge_points}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% if student.files.all %}
    <header class="major mb-3">
        <span class="date mt-3 mb-0" style="font-weight: 600;">
            Files
        </span>
    </header>
    <div class="table-wrapper">
        <table class="alt">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Filename</th>
                    <th><i class="ti-download"></i></th>
                    <th><i class="ti-thumb-up"></i></th>
                    <th><i class="ti-thumb-down"></i></th>
                </tr>
            </thead>
            <tbody>
                {% for object in student.files.all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><a href="{{object.get_download_url}}">{{object.file.name|clean_title}}</a></td>
                    <td>{{object.downloads}}</td>
                    <td>{{object.upvotes}}</td>
                    <td>{{object.downvotes}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}

    <header class="major mb-3">
        <span class="date mt-3 mb-0" style="font-weight: 600;">
            Update Profile
        </span>
    </header>
    <div class="">
        <form class="signup" id="signup_form" method="post" action="">
            {% csrf_token %}

            <div class="row">
                {{form.first_name.errors}}
                <div class="form-group col-6">
                    <label>First name</label>
                    <input type="text" class="form-control" placeholder="First Name" id="id_first_name"
                        name="first_name" value="{{student.first_name}}" autocomplete="new-password">
                </div>
                {{form.last_name.errors}}
                <div class="form-group col-6">
                    <label>Last name</label>
                    <input type="text" class="form-control" placeholder="First Name" id="id_last_name" name="last_name"
                        value="{{student.last_name}}" autocomplete="new-password">
                </div>
            </div>
            <div class="row">
                <div class="form-group col-6">
                    {{form.department.errors}}
                    <label>Department</label>
                    <select name="department" id="department">
                        <option value="">---SELECT DEPARTMENT---</option>
                        <optgroup label="COLAMRUD">
                            <option value="aefm">aefm</option>
                            <option value="aerd">aerd</option>
                            <option value="agad">agad</option>
                            <option value="gns">gns</option>
                        </optgroup>
                        <optgroup label="COLANIM">
                            <option value="abg">abg</option>
                            <option value="ann">ann</option>
                            <option value="anp">anp</option>
                            <option value="aph">aph</option>
                            <option value="prm">prm</option>
                        </optgroup>
                        <optgroup label="COLBIOS">
                            <option value="bch">bch</option>
                            <option value="mcb">mcb</option>
                            <option value="pab">pab</option>
                            <option value="paz">paz</option>
                        </optgroup>
                        <optgroup label="COLENG">
                            <option value="abe">abe</option>
                            <option value="cve">cve</option>
                            <option value="ele">ele</option>
                            <option value="mce">mce</option>
                            <option value="mte">mte</option>
                        </optgroup>
                        <optgroup label="COLERM">
                            <option value="aqfm">aqfm</option>
                            <option value="emt">emt</option>
                            <option value="fwm">fwm</option>
                            <option value="wma">wma</option>
                        </optgroup>
                        <optgroup label="COLMAS">
                            <option value="bam">bam</option>
                            <option value="bfn">bfn</option>
                            <option value="eco">eco</option>
                            <option value="ets">ets</option>
                        </optgroup>
                        <optgroup label="COLPHEC">
                            <option value="fst">fst</option>
                            <option value="hsm">hsm</option>
                            <option value="htm">htm</option>
                            <option value="nud">nud</option>
                        </optgroup>
                        <optgroup label="COLPHYS">
                            <option value="chm">chm</option>
                            <option value="csc">csc</option>
                            <option value="mts">mts</option>
                            <option value="phs">phs</option>
                            <option value="sts">sts</option>
                        </optgroup>
                        <optgroup label="COLPLANT">
                            <option value="cpt">cpt</option>
                            <option value="hrt">hrt</option>
                            <option value="pbst">pbst</option>
                            <option value="ppcp">ppcp</option>
                            <option value="sslm">sslm</option>
                        </optgroup>
                        <optgroup label="COLVET">
                            <option value="vab">vab</option>
                            <option value="vpr">vpr</option>
                            <option value="vms">vms</option>
                            <option value="vmp">vmp</option>
                            <option value="vpt">vpt</option>
                            <option value="vpp">vpp</option>
                        </optgroup>
                    </select>
                </div>
                <div class="form-group col-6">
                    {{form.level.errors}}
                    <label>Level</label>
                    <select name="level" id="level">
                        <option value="">---SELECT LEVEL---</option>
                    </select>
                </div>
            </div>
            {{form.phone.errors}}
            <div class="form-group">
                <label>Phone Number</label>
                <input type="text" value="{{student.phone}}" class="form-control" placeholder="e.g 08090000000"
                    id="phone" name="phone" autocomplete="new-password">
            </div>
            <button class="button primary col-12" type="submit">{% trans "Update Profile" %} &raquo;</button>
        </form>
    </div>
    <header class="major mb-1">
        <span class="date mt-3 mb-0" style="font-weight: 600;">
            Account
        </span>
    </header>
    <div>
        <a href="{% url 'account_change_password' %}" class="button mb-2 fit">Change Password</a>
        <a href="{% url 'account_logout' %}" class="button mb-2 fit">Log out</a>
    </div>
</section>

{% endblock content %}


{% block extra_scripts %}
<script src="{% static 'rc-includes/upload_script.js' %}"></script>

<script>
    let department = document.getElementById("department")
    let options = department.getElementsByTagName("option")
    for (option in options) {
        option = options[option]
        if (option.value != undefined) {
            if (option.value.toUpperCase() == "{{student.department.abbreviation}}") {
                option.selected = true
            }
        }
    }

    let level = document.getElementById("level")
    let opt = document.createElement("option");
    opt.value = "{{student.level.level_id}}";
    opt.textContent = "{{student.level.level_id}}";
    opt.selected = true
    level.appendChild(opt);
</script>
{% endblock extra_scripts %}